MAX_POINTS = 60
REFRESH_MS = 1000
DISK_IO_MAX_MBPS = 500
GRAPH_HEIGHT = 90
PROGRESS_THICKNESS = 24
CRT_LINE_SMOT = 69

CRT_GREEN = "#00FF66"
CRT_YELLOW = "#FFFF00"
CRT_RED = "#FF4444"
CRT_GRID  = "#024D02"

FONT_TITLE = ("Consolas", 14, "bold")
FONT_SYSTIME = ("Consolas", 55, "bold")
FONT_INFOTXT = ("Consolas", 11, "bold")
FONT_NETTXT = ("Consolas", 20, "bold")
FONT_TAB_TITLE_COLOR = "success"
FONT_OVERLAY = ('Helvetica', 12)
FONT_INFO = ("Consolas")